apiVersion: v2
name: jellyfin
description: Umbrella chart for Jellyfin
type: application
version: 1.0.0
appVersion: 10.9.0
dependencies:
  - name: jellyfin
    version: 19.3.0
    repository: https://jellyfin.github.io/jellyfin-helm
