apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    sablier.enable: "true"
    sablier.group: "jellyfin.valab.top"
spec:
  template:
    metadata:
      labels:
        sablier.enable: "true"
        sablier.group: "jellyfin.valab.top"
