apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moonlight-web-server
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Mi
