---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
  namespace: security
  labels:
    app: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: pocketid
          image: ghcr.io/pocket-id/pocket-id:latest
          ports:
            - containerPort: 1411
          env:
            - name: APP_URL
              value: "https://auth-id.valab.top"
            - name: PUBLIC_REGISTRATION
              value: "false"
            - name: TRUST_PROXY
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DEBUG
              value: "false"
            - name: GIN_MODE
              value: "release"
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocketid-data
---
apiVersion: v1
kind: Service
metadata:
  name: pocketid
  namespace: security
spec:
  selector:
    app: pocketid
  ports:
    - port: 80
      targetPort: 1411
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketid
  namespace: security
spec:
  ingressClassName: traefik
  rules:
    - host: auth-id.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketid
                port:
                  number: 80
