---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
  namespace: security
  labels:
    app: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      containers:
        - name: pocketid
          image: ghcr.io/pocket-id/pocket-id:latest
          ports:
            - containerPort: 80
          env:
            - name: PUBLIC_APP_URL
              value: "https://auth-id.valab.top"
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocketid-data
---
apiVersion: v1
kind: Service
metadata:
  name: pocketid
  namespace: security
spec:
  selector:
    app: pocketid
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketid
  namespace: security
spec:
  ingressClassName: traefik
  rules:
    - host: auth-id.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketid
                port:
                  number: 80
