---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyauth
  namespace: security
  labels:
    app: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
  template:
    metadata:
      labels:
        app: tinyauth
    spec:
      containers:
        - name: tinyauth
          image: ghcr.io/steveiliop56/tinyauth:v5
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: tinyauth-data
              mountPath: /data
          env:
            - name: TINYAUTH_APPURL
              value: "https://auth.valab.top"
            - name: TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: google-client-id
            - name: TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: google-client-secret
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME
              value: "Pocket Id"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES
              value: "openid email profile groups"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL
              value: "https://auth-id.valab.top/authorize"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL
              value: "https://auth-id.valab.top/api/oidc/token"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL
              value: "https://auth-id.valab.top/api/oidc/userinfo"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL
              value: "https://auth.valab.top/api/oauth/callback/pocketid"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: pocket-client-id
            - name: TINYAUTH_DATABASE_PATH
              value: "/data/tinyauth.db"
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: pocket-client-secret
            - name: TINYAUTH_OIDC_PRIVATEKEYPATH
              value: "/data/tinyauth_oidc_key"
            - name: TINYAUTH_OAUTH_WHITELIST
              value: "abugeia@gmail.com,admin@pocketid,sabrina-gournet@hotmail.fr"
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
      volumes:
        - name: tinyauth-data
          persistentVolumeClaim:
            claimName: tinyauth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tinyauth
  namespace: security
spec:
  selector:
    app: tinyauth
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tinyauth
  namespace: security
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.valab.top
      secretName: tinyauth-tls
  rules:
    - host: auth.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tinyauth
                port:
                  number: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyauth-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi