apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tinyauth-protect
  namespace: security
spec:
  forwardAuth:
    address: http://tinyauth.security.svc.cluster.local:3000/api/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - Authorization
      - Remote-User
      - Remote-Email
      - Remote-Name
