apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        image: dperson/samba
        args:
          - "-p"
          - "-g"
          - "force user = root"
          - "-g"
          - "socket options = TCP_NODELAY"
          - "-g"
          - "aio read size = 1"
          - "-g"
          - "getwd cache = yes"
          - "-g"
          - "use sendfile = yes"
          # Syntaxe -s : "Nom;Chemin;Visible;LectureSeule;Invite;Utilisateurs"
          - "-s"
          - "Data;/share/zfs/data;yes;no;no;user"
          - "-s"
          - "Video;/share/zfs/video;yes;no;no;user"
          - "-s"
          - "Data_NVMe;/share/nvme;yes;no;no;user"
          # Syntaxe -u : "Utilisateur;MotDePasse"
          - "-u"
          - "user;$(SAMBA_PASSWORD)"
        env:
        - name: USERID
          value: "0"
        - name: GROUPID
          value: "0"
        - name: SAMBA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: samba-secret
              key: password
        ports:
        - containerPort: 445
          name: smb
        volumeMounts:
        - name: video
          mountPath: /share/zfs/video
        - name: data
          mountPath: /share/zfs/data
        - name: nvme
          mountPath: /share/nvme
        livenessProbe:
          exec:
            command:
            - ls
            - /share/zfs/data
          initialDelaySeconds: 60
          periodSeconds: 300
          timeoutSeconds: 30
          failureThreshold: 1
      volumes:
      - name: video
        persistentVolumeClaim:
          claimName: pvc-samba-video
      - name: data
        persistentVolumeClaim:
          claimName: pvc-samba-data
      - name: nvme
        persistentVolumeClaim:
          claimName: pvc-samba-nvme
