apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cpu-models
  namespace: ai
  labels:
    app: ollama-cpu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 10Gi
