apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    # Middleware Sablier pour le réveil auto + TinyAuth pour protéger l'admin
    traefik.ingress.kubernetes.io/router.middlewares: tools-sablier-filebrowser@kubernetescrd,security-tinyauth-protect@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Web File Manager"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "si-filebrowser"
    gethomepage.dev/name: "Files"
    gethomepage.dev/href: "https://files.valab.top"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - files.valab.top
      secretName: filebrowser-tls
  rules:
    - host: files.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-public
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    # EXPLICATION PRIORITÉ : 
    # Traefik matche par défaut le chemin le plus long ou le premier défini.
    # En mettant une priorité de 100 ici, on force Traefik à évaluer /share AVANT la racine /.
    # Cela permet d'appliquer uniquement le middleware Sablier (sans TinyAuth) pour les partages.
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: tools-sablier-filebrowser@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - files.valab.top
      secretName: filebrowser-tls
  rules:
    - host: files.valab.top
      http:
        paths:
          - path: /share
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80
          - path: /api/public/dl
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80
