apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-data
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-hdd
  mountOptions:
    - nfsvers=4.1
    - hard
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pve-media-data
    volumeAttributes:
      server: 10.0.0.10
      share: /tank_data/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-video
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-hdd
  mountOptions:
    - nfsvers=4.1
    - hard
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pve-media-video
    volumeAttributes:
      server: 10.0.0.10
      share: /tank_data/video
