apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-hdd
  volumeName: pv-media-data
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-video
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-hdd
  volumeName: pv-media-video
  resources:
    requests:
      storage: 10Ti
