apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boten-anna-data
  namespace: boten-anna
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 10Gi # cache OHLCV (feather) + modèles FreqAI + logs
