---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-git-creds
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgCFv8EfxC1krVKQKiDQdwwrJ4bWrLBIHIvFZXRAgUFgABZwgE6atAWiRSD0PxKnOI94HCM4nszuuLg3szeRx1x+Krx9AWG/r+KBfX3VWEWxeX9MyXkYkZUHtCU1E4Y8AShQHLlG4TR09L9dEqmAJpKcSSJcHC5T0QsZzhEi3GET70s+oPXYTPs8GMlLES7XBZV5+p7ctoG0z37rP9uWDOzcgTwbKyfBtGlOtc58dQah6sHFvsZ/4AnrKY1ck7R5cOt6yXMB9n01eblUt82usPSg6QBO0oKcvAduBX9uIW5kJpHOQY0sCw7G4IFvW/JAfKUawB+4GrvXX7v1n5wxxSIUSPkdIfhx6pl7IWBrTCDI2U4I15pyAM0QW75KJYqun8B/mGuNHLtvVwiXpQx9n0yUhdeD+/vTx9yCvfbvyoktjzDNIqjVAvHX83fdsWd0/X8ei9XnkO0o+NZ3NzxIppr+UdPdtVqyfHBg8dWxIB9pNguMtkzMrtc5dcjfAVwVtKgK2+Qc+2sEoYOgHonIomg6t9+GfdjZjDdDxLrXkLC9QYp8883ZM09FWQTctcEcA/NmP5o3dAQUeKwijkG8uf2OGIrTQM5RDniaIFP1Vd4tuEbL0wbTNzEH+i1UWOIjsqR/AiwCxf04SYslwtG7w+qJ20mlHnJ+EGpNOPyNPLkkrxmQUtVQWmV6o7TICPdURIE8LmGgdRbAk4xGOODW1p2ekbEyHk/snBfE4iVAAnH/fXeAeQYbK0kfYG1f4Po+U6JdvY18qcUzEGamYt5ddvuhw1J65wqXfwtD7KMUNb0plWOFEQGOtfXsh2ldmNd9Sp1GZYmOyZzFS13Rfnhn9jMoODlxlcNhCdRvxr1WdtGCKLdU++s7CGbifd00Vmqq++9abLeaTQ8nBmO85d6vHTndhkqDyytoUVaTlVfDAE9hW+q+P4jXLjHCjbmt7+8JENT0wLoL1JtQbdreiVSWCdvHzLfdRl/vqodkjp9fKT8LoeNOy5D+YEKjGmjMA4pUPiCNR+sjNukZzqV/kyxSRk3tzC7eXVNymm+McBQ0ka3xylbEq0zk/HIp+iLyhQozhZO0hHdBaKZRyO+Ofrv58qz1pMWtyYmTHmCx0HzDjre+ghj+ovH6gDGNRu/mo4Wn48cyInYZSrXTzJ63ZH3DFslh5y9qg29CB9jXIvXGT1fg0vMB0eP2okX867vH5xJZzIXTUc02hddILTtIdvx4ER3kyeWQYonXAwbeloEuO0uaLl4XIEKIm8K+1vmxY+IjJx4=
  template:
    metadata:
      name: image-updater-git-creds
      namespace: argocd
