---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ark-secrets
  namespace: games
spec:
  encryptedData:
    ADMIN_PASSWORD: AgB3Psyu0/FJk8Q0G2a1V8jShszQFmTf3JIV4t+Qq9gquak14hVnj+oyWpxb0ZiBrG8kew8GqBleenSDhruJVhoJHX8m8GjuezMbqy0NWeh6EogpuKMWJ9gj49u5W5fpEjgKLr6gXMjoiRF+mKqUDmJfMbBsFc8b9H0U5w6wb0oxlufRN28mETg/uWUtvwD7hMmfvfPViVkyLnOlH3iR6ayaJiU1yRq2lcQ8VytD1xBVUkkt9aAzG/0d0rwjAKj+H/WKHHlt7DTaRMpoAQ1lEwwEjBzkGUiBsEfYbSnbrjoJsN/Is3E7OABBTbdMJkz/6WYED4seA9Kz+7+RyzhhD0fO3dA5CSZ1yuTb8QnZIDMWeBIUgURkSqR+fnEozxW2VVWRhN72GEMZpVFLuWQVYYKEYOSdodj4jo9u//0SSniFVf8VBkZpNylHWscZ6UzfuEa8EN1i3K7CLkmWbU+BTeQLIz3XcZZjbq3pde9wT1/hUdXcZ5nPiNexX1gWT5YZ6qrlfkAVsPbfR9P64npwHuLFcW5i7gLwazThwoIswo1heVaBfAIeoc8//QRRBHbFnHwXoW58mA9zzTI7rycZknKs+n/941ylOoy16zhXH3Lw4hqdwgS2J3rN05gsQsdvCFV814k+gUbqnhpHSHZo43uyqnZPvi53tFrLL7I8nCLMO0w5/tv66Fzf8oPF5PXN43kacjOUSz0d2V52Lg==
    SERVER_PASSWORD: AgCPa4hLK7yBdtdEwtZMMC6o6vFFKQ7/k3ujnK9tcuoWuruLTdNWFQ8SoEeALc2jAZUdCcy7EfkS4bwJlAT4Mkwk0TF+jha7NN3Di9hsAAlfrCj76ycumLB6YFhI450TaZ+MpyJtIRlIYigpEtIHHtE63SVllhiImfK8wW8NOjcqhQcfmt8zQEOgidjQLHlcV84YgiLrlnmIe13MN92D3YbqHZqGudeC/yg9XCBMGdBu5WcN5zbNA6JZ3NY4sFCygII5dPdEceIKCBWSERMonX0iDjJnVQC5H0tHmZUuGkMIN+iIp3DQkiVEHn1io23F0IpRwOysTfqy51sn/FInZNgxDxaxt0ut/sm9dmA7KkuHa6LxCS55k4Wup3XQwCAhZTd5tF3iAkCzfrXdDUoaeqOMaXnn2GLlZaQdBDMtrufXS0gBGd/PaSqJpYAXY3l6+hzrV7Zd4qvvVDWJjedHrbjkFU/jlf5uCIBIi+cWEOdoGiFFRLX+0Gsc5gzFSAeFWuCQqDE0nujWIwhu/e7da7XQGaHcFgZ/wE3x9bQ900WR+8JjMZNe1deiA0ITs6wc9RrFMpiIQiFFaNlCpwIHtULaBT+1FurAMkXEUaR+ommUf3mcV4mjYiRu0gGqQfVROHO1glCybg31VBki6EW+FGVy/ZdlozwW+jOpovkbFYCu0cGsK7P893DrNLMb26zyLoj/fcnH
  template:
    metadata:
      creationTimestamp: null
      name: ark-secrets
      namespace: games
    type: Opaque
