---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: asa-secrets
  namespace: games
spec:
  encryptedData:
    ADMIN_PASSWORD: AgB/9STBG+Pd0gnYSgBv7HVSCtecXQedtAuZqLk0CrmzgVB04QP0BNt82bZ1bPBVT+b6HqsozpJm0HmYLgbNT4j/8oDdQqsQ/MGkPqbabOfWGYOXA8PKN93hIGmfBR1HIjqTBJ1rJfAU4o6mm92YXbiH3u3XWoyF+QvMkKmTEmDJm2dgZXDg6LBl6FAMV9WvUcoB1aoAhxFsC/pSeHSUVUmzu1QOV8R7SVJLH7HxkVE4M2DJiMANDqis1Uk+zXtKsn2qB1fcdXjApCPo8r6MKAKe2hodU9K/OEokGwwsuSXGAnNU7LwbpSUXNG9i5N46ynysyuLp/5CK7e7LmWSpP3AQ6kscKO4KhsC9bPV8Pn038N4GirgHDC9ftBQ4Ic4qPSOp67zbQPFdFbcQ3sRPGZeR/IL91XpDoL2mYRp3SDMAb7JPy3eL2m/5MxrtcqX+FxJwvJz2efLCeok7+4/HrdyZSqh4toeE89ui8bWyTr0cKNJAn3sLY1tsUKm60o5ffV469dITmtMRuRToaz8QgUmsUFoQkDYkE1qjmf8JcXxIay45O+KObUENqvQ2zM2XfL5DK8Igd8nBab5iOkBxSLPD3opvLE2+SrmlbNlN1PjJrfmFnMUSGLDKM2bKlKDB5tt13E8lnFHsTnFNtgSQPAvgCOT2SFIy63e4TTWn6+A5p57mowAJsU5cVItaEaQSoWM7/rFKAFlWiO/O+A==
    SERVER_PASSWORD: AgAwvUSfXQE5pysANH84vNnBOyxCNLpEe18CP5Ual3DjEiQzulAr+UZXKURxQ7pT5g97NNUkLi9GrxfFvu9NkllS4r1neOntqK2lqDEj28hQLNXjI6JZ7tH/fuakZlp4NpF4Suj6GCxd+QlFv0lhrg387U3rBtXuBr2qluwrULpEn54yC77zj4XZ6CpxVSrdF/sS8rEFvIIdnIy/UxZ/oYo2BdCKrSGdwbS8na97aiW8V3mny5nw3xHaoS7kth1Jl8R+iAwFW/gwm3bwDSRlso6hpm3vgLzi3LIR9mKzXzUvoFsR1+d9oZrMIiwsYYP/jLU7O46Zo28c/ru/m+jd7DyJboHKsn5c0YEfCg1oNIn4PZnWwBmBE1kyPGrSDRjIA29IEA4lQhKWKuZ92KDoBL6F9+Mybp6v/BnItKYsd+BHODp7ayvz3p015UEM5x10M1uldYlF8NF9iDwtwh6Wv4Jx6FmOPQq2j/HSzbXdft/s/P8rWlJqysiy2R9soQuD2lDKFGvV3KwXTEzpXUDF89mgdEYTLae8BuDKLnArvDqLtWBkMAuN2YznYEogHPeqI2oVP+EZmZMBvnTh9foR/EnCd7aqcG17dNhDYeoaOPBPHBa3xIgluArk6VlJ2cjZnjwEiE4GS0kGokTEPBgMzmffL+vv8HgD5C+Tl4W1mrCFfMV6XxlbyhUEYGplA0KXlwU=
  template:
    metadata:
      creationTimestamp: null
      name: asa-secrets
      namespace: games
    type: Opaque
