---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beets-acoustid
  namespace: media
spec:
  encryptedData:
    acoustid.yaml: AgAzqCyGlCKBYjtM5QP5G9ivdgslS/GnUHDcDqyOvmm3njVnWUi7EcyxvJwTdmxgSCVWQJt2b1F9TFV52NMOxV+Wz1qap6Z86sB+t69Jenq6Vz2PGvm4dOxB9/tLxj+8cDyoSXabGESQdgl44ZIRFXKCqGjJpyuYhpJED4VS1pHSCL2alwLLe7Ii92aCsWMd5Nu6olc/MBlputMvrWRYYvpACU7hzAawD9aWSPQpJ5WNitxQ9UE1c+HuAOkN+YbE+cWtuP9Q/ud7k2pjiK7NN3e//qeymFGtypVJL4yckPAWQ/6xkmeoPGLbH5aImCkFoJdV7iMgrxahs/YioG4HCpC6Q60dQFTd3gOqU5vSAiPWOTnMo4jPHTecLZHI2QzhsKx6DhE4Z3D2d2jBjMaSGK9sRxlQr0sADEPMHIq5tbl+VlJsqfc9f0nY0l7m9ScL0MHwHq0BOZ8nQM58RY/4L0fqDb3dtXxOGtiuAWi19iwTZPPrduJeVx978jZ8CELK+nKha9fIBkl3LgB/D1TaZl3rp1lReKILypJMDbEIBLsIEj9TMxwG7xBwBMp707zRi2Qc66RsCALkHaZzVUKRhaa0a6JOMCMq5o5nFa2W3pcXO+GUYHhf9QwhThozUJQwxn8qyS0mdlUOXeIJ69EQ7YSq4YFDzOttJmY4GAtpYjUHHvTM/o5JaSSA/NApjnwBJ4asPbK2YQxQJGj9bkR9Sbw5IOcNv9izNj6UaOpZTa+Y
  template:
    metadata:
      name: beets-acoustid
      namespace: media
    type: Opaque
