---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-auth-superset
  namespace: data
spec:
  encryptedData:
    password: AgBmkdtzOUrfNIWg31eLc6bJa7CQ0wzkyP+UKMNrhcHCZnJnyiNmC7GZp4rTXkjtVNbYkKWZ8+QQKV8uD9sUg3j5OqS4a85JH0wxpNy7JUaJUEDiqnnx6VrwkVXU4Qjr/3jzm8W0TIE9kLYf1Y0MiOmOLDbU33ozyDcm3qUEvRQgYs82ypvu51GYfr4KWowORQN8pJt7xu8h285nwTnm6WiKSdrByS7FFTFCd5TxAEQstEIcf3Vx6Yh8f/ZwsVpRpI6uHb/Apd2PKlkDW/+R00/xMx+F8a6eZD8ze/SJShylyq56wNZ5E8tbqC7olNHkT2GUDc/P22HJKrojnzUmTRQApZ+Ekz1v/sKuGif7sSmKS9kzrWJTf6en05K/etAdhdW38IraXoEYgNB7ke3GDr0/ayry+F2w8nNAH0tbSnlpxNt2WAeZIQamCaNUo2kjcup696oIDTOgqakJMXNIhEyZhfptyEfKeH8vkzrvuirUdf3nI4PPQOGR22YUXSz8yKGHDvLXUv/jXTnB4EsII1iJCm9pUY5GVNsjQ5mkWLjVw0GxMQgUYnatyey85H39Sq/houeClnVJ2dBkOGR0Tbv7aQk6OXy7d3ihzmkc4DQ09WYKjX9E9J/Kp1fZlIwI1R9TOO7D0gaJ9Y8Ch6s2gkHzUdWfm3QQNqN7/4kMLrtdjOCHoa4jZDfqaUqKiLg/tSf3M+t1Dar7Iki+O7aQsfU3rpLv4A==
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-auth-superset
      namespace: data
    type: Opaque
