---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-auth-admin
  namespace: data
spec:
  encryptedData:
    password: AgBTwQy6iJmKMAfsbslEmosjViDgS+4uPi2d7ufO7pDDki3S+rNz/SVHqvzOICFDeD8vWGQ+NfL3vJlsxalIxPlr1+KAc79vq4h5qY6r28/+tOpZxJ7WlpY7ybaAUsREckGaWxYwZN5g23d5W0XcPnvAdhOfMFdXtteu1Sq4C/NbUbRVOy8Eo+g1SmPMnyK1XAlqQAgrlwlz8nMC+vmfnOpWlvV9c0j4xlj+5fXKtBeXYmEoQgGhI3hnuUahX9UODAO9pPS/DfvcXBOC9Kmq/Vv0dlbX1/n3rqKqb+0i6m+Nfgww8t4UJ3DsQoKTfDeOAOODPhz2RD4cvVmDpGp7tW0/OHZxJAlusg4HBorAyKLDI38UWfPVYA9oOh2hd32GX+KTnufXFGZal6rQ0y051wFkvd4lzcSHPzhkXs81pgoVWWDfqnU2gNVgNWqbiF2uj9Cn0m0DiK26rAccYL9N0FDKDC+OfiQqgq9ev7FDsKWMjlVQQLWnfVBWYeQH2ldQerTK9fY4N5QRGFWdkbaLHcPPNVpLuKR35B9KIzR2dPE9CfoeRmlxwXkdKfAkwgUo3h4VLi+A1R/i5q4NZ01SEXm3BuLdfJ/2LhCUmF6TlVMh2GPDY55w2GtvFuNZ6Ek3zpFT8ruSbCbfx58ko/1pkIN42F6eO3qHTQzWZfo85kU99teH90xykeXx0k6Pv1woG0xDhBPychjbk8uFGr3Ap1zJjA==
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-auth-admin
      namespace: data
    type: Opaque
