---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-auth-dataloader
  namespace: data
spec:
  encryptedData:
    password: AgCTaQzNk6Vkwx5S9hy8AWgDDUPfKM4w2W3bPtYeYm1M5grwH9v473fBFmqG57LnQfAMM0BlpsqQI2+fUHOLwjO3FoazK/CrBGK3YE5cA0JSDYHiZEIJpMkA4rztWi7bt05hCz0HGwNlbtoIYV0tu1jm9lXVPagSUHap6Gu3fkyeKambdq8UyskCAMEDWqGI1shWmyWjo/OjymxW0r7OPXV/wz957HuCc5XtfJimzYEw26r8HfUNKoH+8SQZ81q0dDBYiZBIimkNLKHWtyHL4A6SUpvfPafUKnyFrQxWidUYnRYxIpom/ThGevalGxgNUywT1ACAOMtGsEmfsVXRi4Zzphqhvew/5yvYRQ6zC2WRe9nt4AE2f+nRpQRnalKNQfhHS4DMkAa6DdhBov5eUt4smGWbIdBLp1SrEPEtibe6Fgux60YjKdCfxszpBC2dUwnpRtczQcs2WVG7pL9ZabZSc99ZeysronEYYJhGrMpSltxktN1wgiozRrhoybdAg9wonrUNdoG3gRfCu1EENUaABLTcgdsaJ357mXQQ8urhXP1ll/mw2p4ek2IExKlW/yCWSUJ1bvfRWCX7IlWz9ZUP34bx6MeVwv6FG9bM8JuwpXyqnO50TojsbQIk5KOacGOgUmesuM2S8qc1svL5ph2Kq3PrnAZuobXu66sfBwWFmZ46iTAkhnhqsjA9bWMrFDJXrBIXh0O4od+o+G9H0XOdWw==
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-auth-dataloader
      namespace: data
    type: Opaque
