---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-credentials
  namespace: data
spec:
  encryptedData:
    password: AgCLbQYVbQ9gReUjHD29cXkDRbi4f3fiiAfQFskyU3vz0HhCSp8TNTZBUG5QR5wgMDCPiEW99subdWVET3ff8AINkFuLE3MeLrK8j4i4HbhThIJ0vZtQnRf6Y5QGZoP+G1x5AArqFFWNWyZtL+5kH8TK9erHU11V1jIsrrNQ459Tnq639YAENqTdrQRxiisyjimHMoxRuVLfLBXXLZExu/1rYHgbrT3xjSLaD7OfejWE43PkoOrs16bOIphzzdbT6Llnke5AOz+ohSw7AaQJwZ05nzb/z/2JMc+vGnA5gMLuGwQmvDzLUYHC/AoBHgKDulZd+HkHkOEAt0hiSKQ3vrvGSpxdc7T/m8bTwE6LmKWSwgmDq3ViSC+nBit48qQCnWm2q2hIq8JdgRNDZMbuocvJXgLwbOqPen+83VheC8jhUBZtpJE299+JjIm1dvlEB48IPKHrvdgRqMtTvjJgX0v13YAD2jvDiv3sYgxa9vd7aPsJeQGfR+/kZrbOvsYIOSI2/KBlr52a9nZxH/5Jik/NBuTKFUZT+/pCUUwkYEqJTix1/YxjF/34FmamN6yLw0b0np9S73SKnFsCRWpdgFLs7S9fPaoJupJ8XT36mQPbleyRCO2d+Ijz+67pxdt8//700zliZLEnC4wxAUP0u3Bz90arAB8cFfwERfU99Kw4ZzAPlNtdF8YcPtwm54lLKHWd6Gfk+hBsazRoQA==
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-credentials
      namespace: data
    type: Opaque
