---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgBPEEqBeMG+YKkrSG9rtMsmyypvIjUgfOcbijLpngWAUrItc8Dp7UIGn/PlJyz4SCJ/RfExVuiqQMt/xDPlxowidS7u1BHODISKwKUU5nppNute/ye0uKItSMHYyPBq/IuLRU6bhTOfeRGp833heF1AmxgUeQCtabDdSS9XJ25SwMyfe5+b+vy5hb1W45ZQ7IpGleqYfwNue7FQAmJAIp4uxm6DpbOKkinHQ2MyjRjeuNw+LNLr/rohJOYr/MIKW6ZakfB+QTNhsfTkPBZivL/uhJf2ct+ulLGGTdOatmt7ocUIX+IzUl/esXLhJPWMd1cyg818pjhNLYRXCgam/ROkXJIlHwFiYgv6iqNUwW4NwOf8/6gGoTYGEWplZWs9jpUR15F1EvwVIR+y76vJJWuC62+kB4GEamJTzyz3ytf3DJI1wCOkgKZLEIX9E4iwdaMIBVUL4DXEmmO/en0j6gzkjvluLbCf79ECnSOph993CnKSM4dPx3Hgost52o4GAWMTd8FcQnSZUGwwoqIUXLlQ0v0qslKGUkJWT2nLnTE65MPaVNUGd+2HrF57FWXp7gbwaLKBWF9EwbUTx4WHWGAp+apS/zQcf0RsCYDRy3C3A57CCVDJ9m6CEImh8gd3t+qv7XOZKWZsdGX1TDuRRuMAeTDPdPhedAfjHoik7LfBZ2hYUC2t5cofcS3/ORM/dbPYx611xyiAjJ7GuUSvf1BNrPnBtFSsvN6+wil3wJPNTZFt7kJX/3K6
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: kube-system
    type: Opaque
