---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgANlE7KtgOfudlbaugKFURi0oC+tOsqHVjy2SOHKAwXQe+Aa5gP2t0yDSJr+RBGgm0JBbSFRhtCCl4MpHoF4/nGf1aPiprnXYw2844XZMWlMu/6372FVkAHyg/dvI8Ea7ERLSjQOqwFSZuaVadNm/XNwJ3+3qxMuFjklsOWAEdTLg5+wd7+qbZhxYGP/1g8UOTTgHeLwBVYfAHzKFp47OOx/VlKkiQ/Qeo2UUfbNfOkdkdQ3eYSIkUXxOCCd9KauFUl4Sze1rha/8JbsEWPAfRXElM65X7oYTtctUhNVt7nHqooppCx6j1+/E8HDJoJgddd2Qu+QTcQsNVlI64hPVf4h+14cizZJim7XkAxDlYtlekWK/YlAaDgB58m9YPfWnDK/Lg/p4cQgstcqhYx0H53keQr/jGUwlQRUOkvEZYJpRw/KNGx7KZ/ihFXG9lK1e3gBdcTrmdjzAjpQ3D+4EgOwGaA1JmjB1Hlk0dZy2qheUmN+P28nNI+t8GDMityozj8sYYKaPjwojms3zMjukQxi2EsQI044Hw/0ILSwud4TTzEDEdfEwJIs1IQHWEpyGgfaHwEkw6ys3cNbVMmAxzozJSH505mvYxCjFRg9KUorOALoMqOHHWfztYP2k6oyokaf3TC0Pt9XVqUcW0ScVxvGQg0DeCjo/MGD0DFnQ4ixtwTEv8gi1gJAr13kRD6csDqhUEKjREB2qyz5Qa0m2tHmrLOB+h/sXFW25SzqX12s7aJIju+qGrM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
