---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: droit-compare-basicauth
  namespace: dinum
spec:
  encryptedData:
    users: AgBiID5n8COLpGDoGiLBKZg7ifThRDSKaBNJVer7dnz6kxQFWfiQfcVsY8a1Itpvr78XstDM0YCHPDzmo8VWTTHcplbzg71jmUU5bFKH/lB2QUKJupEzyh81ZLTWdyzvCgmJ0YXRShv09ej8U72TIbNHPUisE8r7Fsoct3cZv8inC3nEbHyfLlIbcPbHVPoaNP8qz3jdwlXWxTsnDHm2o9sv4WTARcG7yyyVlO7sqNfKcf4GDKGd1ayRfnlqU+7EQittYy4HvFuOvjk5nYP8dgBR/hViDGhnvmAGzwM4pCZEDLP0H5kzOQwQFoumyr/RRX4zE1kXDmo5nmfqGMHMRjKm1498jZSUBzdx673RElZbcO2kDchCjbZWPXE4ofE/+usEWOvX9WP4BhDldC+Ov2EywBuHIM01VlDympbFrnTelxJsjhfq/JlgRbWIgxy1Z80Xa8J1fUM0cnQxy4qE8IKZn+EApzrGUylnYUffWDOYSx9aqVmHVNXBqxl7hvjq4y5Hm8qYa9N++h+9yyNj+Xvdy3ggQNu720MQ95g50oDZZ/DG3G8CxTneg1NBr2d3EKpi5sjKRKBs+sWJM3I/Sj06AxGVWK9yDF3SkiFUqM61XdD3Nh6hqrqGNzyXeA9WK0pW8N8cyBq90iseiKOdhQnGXl9slOu2GDgKvKC2XRQeNRo8mLlhgNDQQHNXFaInFJfS/S8VA2qY5ihXsGA0g3Djj1oS+znmB6DjKLyv/Pr+d763KUSbhgioHe/vEcJGJJi72HqySdfaL0tRvaZLHLifklY=
  template:
    metadata:
      name: droit-compare-basicauth
      namespace: dinum
    type: Opaque
