---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: droit-compare-basicauth
  namespace: dinum
spec:
  encryptedData:
    users: AgAOqWqpOazAwGWjl09jYduzgh+5ZgYNUOPLtkZo1CGzM10SYBGjg1g9lgkKSuFkML+O2S//XbS3KoAt74kws4s8gae3HU5m/zyPaMjSEiiqKg48nBzOMxTesx0FFuvXk9jWfi+yximei1tThfop4Rk00e1rKcHtBzvpKvk0hXbCQ14hWNjW4TCKuKt+DDTfAXX8qhuw5j0Wcj8yKE1h+a/j5JSMaqKP7pwNgRga1jLmo504cqkE29igJra8j1jYOXgXQAMBuLFfMUSGBpQFn7DeyMxvalwifLOgN9sNYG2d4x9GWBPHZI2ykyjwmDAVJ1YDXvi8d009AyhoFvv865CD/qFcXqS6zi5qczNzQC+9rPkQXJ93QDO9iiQk2/c/q8SbzCtaohl794jpwP9enJ/uUMPf8bziAz1MEcCJtxyFW/rYqtRBBWAUGzThYXaS+9r9BcgwkthoBHeRxOsiYhxILIE7JsS7n1SH2ScgAHxawLCOpyexbuQG5Ny5R9++OHGVAHuiJkhpumMN9qbYEDf+6nAj8v12SRqk1Urkd1nbk0pTbrVKXS4iA4YOHnC+yEfJF9NYDg8maV+4fmNysjQFcZ2GcmO6f9gBDDaWowA+OGEhMFBXJaeImRZT1EgaWQtsjNj8KE1gn+3HkobbQyY9SL2229X+eb6iTS3FInY4AJ2ANq3Rc/2w2Z+eZrqu5eZaJK+okrmztTN64ZKVZ+4bwi7TcxXT35t6ZVOCcDTjNb65eYGp8HYlXh8C8OtVhzqE7xo9FBWJgInkxLymABn5gFY=
  template:
    metadata:
      name: droit-compare-basicauth
      namespace: dinum
