---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-admin-secret
  namespace: storage
spec:
  encryptedData:
    admin-token: AgAW7cuuwE42jhTci30dt8W/ndzbxS1W+RV/53Rfa3uveNVBs211YmetUr9O/OrEbZwJtzH2nPVreMAS+F6FHCuy9nuUOu2plzbiJxyJlNlbomhcMIAB+8/lyTv23bV0SmCqbERml9WuKDycX0AYRifw6xU0sGpz1t+LYodWU1uPP/TRcAVZxnCvZaNiwuJgdx1sXeBeJ4EqF9OJX6L3d0B4GhDEde0gxl/t7zZpOdi4KF+hWQ1NQGhNtdb6DeouxHaiOS8mpztq1OwmXiIwgKVYKOHx/IeYyEyd3ZyM3S13cTcyucovmHjyFCT6p+rZaEFFRE+S72sdSr0TriyxO5YwkomgY89wkZwIrbnWg/eOiYyT9Qm8pD8tX2SLg05qlgJRXzXZssrioYlaxIEjE3nSN/saVUOFi58Su/Sju01dONEZy+KSrxMVNG1husg6f1ziYKm/pPmzZJaflo9PGKz1FiPURaTsetOJc3dLQVJrvTCjlb0PV3+N/QMO6CTNy2LiIMXw3Lg2C/sKMVzLDlAfCCq6lnfChsxxoXsvkW+o8milaSHm8MGwSn0mm0PfrNQfni9hqr+rSvJulAobgyGzxumRQ8ElnmwepNug8zUhGeL8JnGZijkawgm9WP4CDOFfg7vgpsVa+Rh5Eaj5bcVZWyVgeK56NgthI/JHe6CUQVkvd2dcvz2YVQWka8qOw3nDAySh/3Vz8fdYy9RAdE1SE35HMZn8W8gW3YqE8SBl2JbSDaCBoRCDLFuFCFzJls3JR8jnR2S/NHHNHZa0x4a/
  template:
    metadata:
      creationTimestamp: null
      name: garage-admin-secret
      namespace: storage
    type: Opaque
