---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: storage
spec:
  encryptedData:
    github_token: AgBJCNFfL4xTSlxcCSDleSbQ34GqU0e1/18zI+eA6AtAu0YTmUMTkAtqjZdnLvLiFgnTq3snsNn/Onn/AzjMc7Za8+iihu+kw3r5RMGUa3ShzgHqqIgauwQ6LQib1Tmye/Ept0kicLht9IT3NfYdZZ+wSR5NahAnHDCoe4xItkV03/v05Z/VjIRfLBrpq6T10jVeULDsYplN39Cystu5hTLAJN+Szvkua+e1T5am74UTOxyNXRTpEaGjUXPtVUhZCAgmwdsl1vvqo3wNNKuJmHb7WvFMQRrZKb9ZP8Laahaax/ghGeSCmiYlOdW/+0ucvaCo2BpCIbgk/3INROqEjePYSfRJvUJcV4BE8Vn5GIc9WE1yJbxADRQ/6Rrkphe+jF0zeg4piMj1dT6p2qiJhQyWye1vU/e2E1boHkGchi+ngfIOoWwvM+8eWXh5esoN6+z+1jIebOqlLdOAebL7vtqQ6XUY+C8JkSvHxaGd/gSozrc5Wq19UFhFyIH2W9b3YBCBNW5qbLjdU/J1WFnNttsV0EDalzZVhAJ9MsLulpiN3zCpM89HtpVyEPLpVKXnSldJAmsERP5zQ9rvTjRVd2GXbMMhl0e/RZrcwVLMzwcLytdbDIQkdp1OTrLNUQ/Jg1DNf1CXt4np9W11ANh9ifpIdu21cywowaKsL88qCnKKcTbsX438xf67NdCR76S33+EjaJSgRc8rNjlKCcKb8A4oKUZRaBY82VxtWbUGxJZQvqCCHf2utpG7
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: storage
    type: Opaque
