---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgAQv5R6T6MZL0n+6npZ2/sq5No/m7VjyCJQ+pQm8lfxZmi3lqYdJV2kncuY+9HkQ/LejS0U1Ur5ZRq+NvRgLBs+n96F/sirBXHC2jaxGHdr2E1U4w8zKwdqCHaLz6g4fVnu+uGJz+mKwzKAMIylNH2tbntxGBg9YgoJujn2E2BwxC0uLotsVyTvFVV8JiB1SygrkGhhFqtvq4m64tO1z+Ypxp023v2iHBokHe4+OMz4cvVzpRsqhHtJ9DHGXaHh+RV+Jg2OrJJ3LgdJoR3CeuJfAqA5T+JioEmFFrt6AkLq+Q3Th7W+gefETGV/mhN9jad82lwHco4TWLCrZIMY/g1rQ47DTVkEiXm6VaczPgSUzrIaf2lNEwPDmNuAQLwYxMHvjHaVB7auSCnKuqbOPYtq4QEtPTTvvJZgJmkYubu5p+ZeV39oyZI21vRC84UVLit1+37nvOe93sN/yuEP8OaQStLNEXImM6mb28ej6j+EXgE6LAgujr9UOBv0ns4VAcZA/JFsVUWREKzpXNDI25yknlIzRULv66/nFthJ2q6LP/Y+nCpLdqLpraJ8eu3NLJJtw0y2lvICPpBjS4n8PlKK7xpsaJb3CpP2iItewg9jQH0oZefPL7X8R3Lcl6zNqpw2S/Id1lEMojkyYyRDv+uQvQK+fNBCnXhesk9WJY/XDPPH/b1kLh8oKVMW15SYqq9wmzOLtIa0nE7aCQ9ca/j18yuBs+9QwwJY5c0RVtun8l89W0o=
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAoHerM+EFPtuAX5JqbasN13gVax7yZ/L8BemILnXNSJJeaybFCfwtPtr9nf5LgelzLnF259C3HtXYIzuTgh9QStf0oCgo/fO/BrfkVmhJD2aVEFOvf54n2ZGo20uLvGinFndWGYXqxNYIykx9OGOacD8l37aaIrcH2rHgXlNteoeEYBosXQC2oO2ZVUpIiK7NaTjwQwRm6dVJfAOYcSt3sBQ1mdSws8rOFEfafzKhJOkdT9xsNnGpfjuEIe7/FnxR74KMA96RIj1uB5uTl7VuUHnZZ2loSOrQhHNtg4vn7+RlNXEJS3vNwMEh9E8J9qvUawMQQEpwmh1k4+RhT6bortWT/uPVQO2jI4Lcm9JRGth3ogWbDMCXvVDgn1GKux/NA/I7ow0PXFmSrm/5Hcs6RTDM4N0HrOXF2XRuUaZ4y6MxcId5MRkoJbeY+m0x/GZJnRG+j0nhz3wg9J4WLk+lVlg3x48mE3DauPA+dpsKjqucNz/zsY87PMMlSHvK8lL9/XaTVXLP/r3qoRVmbfQHj1qvAgAoHVDdKxheWLqqlKXGIp9tiy3PsKXn2dOd7sl5evieRWFujm+TeA36cr/M7zliHR2sNMJEM+PCOVKG1LiUu/cPvbsF1UpLqvbKP3oLH7nd6xx7Y/lOdYSvzghjBpLS0JzIViG6MJ7ifoHnrkWVpkLwNrPo6FHo3J9IqVZpUo/d71fRVuseRJU0Lh+L1wKbh8hoJ69ekRLC7q0b/hA==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAaNvzUjT0ZBuxJ7zFyanRpzkrdx1FrkwpS0NXc/ggcWleUcpz3qAv01WihXQW61dMl9TUjQCXrXuj+6eIsXqnh0S5QLz+4AnbsrBnVhr8Lr6PSGZ+UBBw4AzwwbAPNBV1H4qEDP3QXn/dXlFvZb+QBLXQ+55DSY4tok+urDnfj7I+b+AD6z0/7e0f8ReCRA6bqg2Di/G40dBmYf3Y5SwIz0jcyMPk4iTJIZqn2xwblpVN2ES+9gWA/aM5W1nnPpHJlagLSDto9KAYXyihBjqKDyGNNpw3m1RT53YCO4hZVjAWWSQC6mHW6U7NPYY77ANsI3qSi0H9dB96ce1NOcyNBEfXlCmsyQmJt5UHWteJ1t1FJD3WRbieIE+yl3Bwf/dS5gJwNlULmXeHppzRfrJdTvTzRHUPvkbgjJw1T2Tmmsn7zThn9HUYlZsOaoWn1ucn04xrXewNEVHBLcr3hH0Aab6yPr07obVXLF9/nwuHQR3/Icr1BdrKPHMSqVIHH71PlfAdNDL4Hp1EB7AhqeBl6NDGq0ru+3/cx5zbRLmkg+6Y4xqjovPA24IgUDZgNzKFXGh3807fLSbJeF8feyaJ6iDu1N8tOY+fOliA8E48iCpTBhYDyNzPqp2aEbKP/sGnV7O3PWWz5LShVCweNalDWR6jO/UAvRNannbuM+kupz9hNWZZ6kzweV/Gledv9vy81E8G+DOfB4AJ7sDgRvqbb2XOn+cd+z42b2JFOkGhEMw==
    admin-user: AgAtb4qK8G8NG1venqu3IxIxGXUJIXVaKeoeIVL9VbsPcJHDX63J+X9C/QvIfRqpCr9KIJokL8JAhjfPKORQQ1jJGgRM4CFPVq5gZLpq61mlDNBQVt/kKsctkJKTGP3+YI3xIvCfA0g674TbaulmFfKgx+ODfTTFwKb3lvpv1oJ2tdVYt7vU+1pyaeUKlKFCdiL0ZJ0+0q485jivneSqprMNvLkHtFuU5oSxxuumrJSdB2ENcwwI4XIVekzznXQCxjH2hKEiNDNPkFS0YnWYzsFtvEN1aNKtPF+S0wKLmWo/EI+iFt5wfNr4IvwMC02WDZz/TgHV0QmKkf13nj3F1hmqGmawK0YoQ9jwlLnQ/QXlXxFOJjNaDuH6Rfpg6TjlbSnpjMbOX35dJMJFrwlzijPDadXukUT5Xm0GTcsAs1fihkyg6DfjZgMcqT1d6RDEEit8vND4+kC1Z0BJOiwGrov/xZK395h6+6n4Qw/UOe4sIjeF7IQPy+NgIvtsmZz0Xaweg9nOi6HCUavW83QVUV+PL3+RqDOa26AU8k7YIOM2eqvL9ftM2vNQ9HguxhyJigyOXjsQt73mMHjHmVbORUu/zgutgqJ+D2+TfYSQOFSkM6rztQzSntXeH+OHWqnrDvbhprEj8OPWnJyYq4SdN1I07kHvkCZeoc84R8e/4r9xOR2xXkKIgg5liA+uaWltvtHnfIRZGQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: observability
    type: Opaque
