---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc-secret
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBJvHADEIGHcqgoB8nKkUxpNJp0RxY2d2b/Cps2jH4VtGTDec36ZLbOfbBp3nu+EqDvTDIefm529NNuwDoBo+b8fDJi60UFq42ojQGQ/F0bxm1+5s+4/w0/66BctlEJjd26y+NMuUd3IRTbVY77GtvtWxk3ru+ulpPGhtEsewzaSpz+Yzv5dxvMhgMirPQEhYRZVUUMcK24gJmYaXuEqnyNuS9NqNQE6aB9DUZzJ/0o+a4RF1pw/coiSkma9DRZAmO9ryOCU1vRkRIhCquRaKvlShb1LlUU7NSLSc7oV7w/ZzZ+pXi8QTh94/QhCevvvs0XKSjGvHMES4qGsX/e5hV2tus8bDCwmOC+UmXK6A28K/XyIkRmbMgnZMzrLDtRvfAyGoONu5u//Jrn+1ZnqmEOUe+KEyH8lUsHKBLWmu/sHWQZPdJeOdhDdTloArast0fjZhe17oke73A+xq6wFLWMam3sus5zDf8QBsw5/yiQs7sBvlIYl1SCcicOJR1DrJd/xjc5xVZ09TnQu4PGRde1AGCvS7wC2AdymTNt8YbTdQ5iqYYmIzcxC5+YcU3uD2EcoJHw48LgOTrkjKUHe4HMJoACiEr++biM2HdAGDeMcKHWUv54Y54mG/txbnhUmnpV7QQkNXvKaQVnPXfdBwpgmx6B2plzWkPhJu1RT8ONplpyRA23o49hA0L51da8u0MTiF04+QajoytTu0jMco6iuc53tRuLZBK2k3KJLlfM90b6U2Y=
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAzSCCMkRrvRWn0aTOQOuo7G/h/94zaq1hxJljPvlhhu0N9ZRZ7GDJpd+Umwvk7JDj2aoQ3xjn/e90CvhPENCQKVnyeDCNmxm0Ov5fJdBNBCUMR+0Mv/Bj8B436RkxJnbZcymsFMnnGDWUv6L0QsSaAdeynuu4vpTf88HUD3vIFF7da/NP33YrNQuVKMV1VCkhoxtI5yR0CVzJdGsNHQIth3d2jKzns5QIApEn3MEQrl5T0WeFU5MvAW04tWcAMro0dhIYPQlZ2iC4U95lAe11Q1z1i9/Uw23ohqSkxNxlWhy85BaS2FBHwzu/5H/27BRSJZDHrP6k/LGu+rY0W/9XzP6+51H6x+ZsUBMCtN4lxOKSzPH/4j+Mo2AsEDphwtYPGhdQAtUCwhqJR79zS1Er7KyxD1YomIepnPgX/rtC/U7i0mQ/hRgFZHfTz3gTVj6S6p0lMLzsYT9T5j9LKEhFGUBhbCsFFNQUg0KqbCf4SDR/hbzYwmrs4z53pfvAgeIPpu0S0nxJOlsDkz3YRf4IpsPmirbGBkRLIawsSq6iMbzGRSFphKtGLCsxAy3DUlr2PycWRB4KlYIZ0SnbtDBf22GE1WPldbbZVM2PdwhZmETrJAclpn/3umqN6L8Ql6MJL1dlf21UE3GgS6/nkwBad3CU+dHh6USUN5NPK4hDWFDbGKQoHCGqt10asrdWRfQP0Sj+w2zi02L2X3vL2DMYtvXzRc40qoj8IDluUUP19Zw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc-secret
      namespace: observability
    type: Opaque
