---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc-secret
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgCQwjSftMATWCDm0Zc/bro3yhHS2CTeG4x37F2ht2YwgKTsDvO2/B5roTmtwD3iKm3RbeRjO1IdzTZC8ZS/Mf0s5P2q/rV8WnnFwbNgi2/kqPnsKWVCRdvth1NKBuLJJH3qn91VV3FwuR5x/IKU0iufmJKpsMaSZphd7A23Y1kJ6klfNv2pgp7tdv1/CGXNPcXVkQzgEXvtHEhtnU/8/hAlqq5TkVeNFzKkRyRmy+6a5OaLUonBcNR15Z44u3LKpKv641N8+pxTnf1QDQrlmugi+epT7JjkgbA0sDMbBRJrYj9NeRT0WwYHyT4BJ97y48tdWjFwaxXIS2z+RyrqsNey3nO2TOrbuMrj3OHkfjZi0N1vtvFrrre73vFpAplTIlYCymx77ERdo70zY79XavsFSvFTuSPMPAvQwOX22ZyfuLP3Jf5a4BD2zDmVwa47Hr8U7bs+1onPyndAAyPcJ/N/m4uMTEXmnq5L06EDJnTR16ERTfYWKF53jeswTBAmlfM7t1iPoT9Ijd/YhkxtDWZAlh6RP6998jrj07EPyykBFIhbupab4lRpbvQ+xYZDcNYUbgP8Mndogjjxg52gpa8UoTx2lQUnN5ZEu/Wk3OYvRa9XtS2Eyt+NBjAqZZ7FHLVAT8G14LN4qB+Y8NnVKhCvBX+T7EJxI5k0/W+Qpenz3fMpml7paYqq0RhfpbLp5f6qLtnRMoqYoElb7QDsJCFLvCect/MPKm8JIIZeYqGKKGcIVr35
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBXQdHPTyKTrZpe0HEtCv2vTey8ygP+qZWqRwS18/OYxYvbcaTJJO8BMWwdVeJFLI8cQ4aua+F1XBEPKUimwC7AZbyVMn9XVU2xY3DFSgDJ9xOufK+CQ45l9zXOTQgZfmBitsSRnm1u9qLxw6+7QTRgfPOHvPt68ExFkxDSSzuv/UKbepX877TBbKUzqUH4ZUV41K7XHO6ZJP4i+MNVzSdLC1i025bDJuaLdRbGeJlWTBijA7Yfshgff2XVMfsjEH2ETWOm1lY97c5JfjXUTn+9QNQZ/BKbTPo+wDRFtTqeIqRVYvh0amdVEVxSp68J2hDEhoaauQ1zxmHXGoz4z/lKGGuVK1Xp+JmVh9PfY4Q4U/CqakaBb3T9ssIru5A579QNTWdaBUFndhkmkFFLV9YrE+1pi72CdijBc7/hfv1r68H4O4bxeSjsC4TiwxH82OMwqc96l4CrlMUHXUb1/dBUFxH0abzL33WWMHkCIAtGq1wrNYBq6NhofDuXWiWX595yW3yCPwUAPuhzeUG00QNsKM/v1vjgvn7Hs7ETcA/jOemWJIExIP9YF8tTaa9X2dvnhdx1dlEpNdSqC//q3gyTMgD/u0p2exBlGaYI4bSrsdB8KZWQ8RsjQc0qT48exGblrqBJ/3vKqDld0BulMyilemeNasqV+ETsjzKBLVpEnUOzw+NVZUGa0ru1FOW2f4NpPU1+Ai8wE8R0g7NQxSa7nGGwehJXwXprBeB24/p0gg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc-secret
      namespace: observability
    type: Opaque
