---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-s3-secrets
  namespace: ai
spec:
  encryptedData:
    access-key: AgAdB3Jwq/aQiBqhaqA4Toz6F8KigSn423QAOGxFgm7NKT3OVhU2blZCUQ1vUSA3SYKMjIp8uktCK/ipRW2YhjcbHqMH9Z/3eJB00Xs2QD+pYMykKicc/LH3vB3izZUjlUUOb3nVNKGUCi19AL+7XFljzh8v4wjPqJ6sK48WiGIwp1Z1j+gRXKgxJO4QaQoiubHLPLHoGlKv9y5HSla7dULS32ySyduApoyeGHQBSXmzNnPHedVuTNI/zzti0/wsRvXhxcyGltw5ENjNSa+2cXVG5f0b9XVrUy73c/ASvvC+tfN30dmFJuqHYNh3HOso3d1RdNK/ld7sOClvLjDsPFk8xL/qK1q8uv09RUy++Ey2LHzEJlmOofnY9Zo1n70VISScjeinZ85fHrr56gYBXcGw/+IzW5U9TsQc7c6nCf+0mMR5uFiKpLdPU7ptkuVxEzll9WyywBoc9hNoH8tVDfnHHHkWMq7UsefzdWQtWy4hrDc0jS8S26wAujIBfYK7jBK0n874x4gl/5ghMhSVR2WwdKH9cvIHaEZa/XPSvzWHEk4CWjkWWc1zmMzyCfaW7SOj9dcqBKtptAJ603pi7sC1uONkTr4m0SlL2Mq7W8yuOFy3QeWpcQAr5knaULh7TueYtA0MNnoARNaNFCHGjm64kqJlGS8MHcpu+Zs5YQayx/SKpu3zy8axr8M3x93krij3I00QxBBDImV305ocIF9bp0qxLN1Fp76tuw==
    secret-key: AgBQBqeFfsclUJzIjULvQi1vJnr0hEd1URXpVU0FANCPj92bb99JCNONgngrKtWxiUxHFawIo9sXLtMLcVEKdqrPGITWo1cIt8N6jVMTWH9uRJ3d5McHr3bqdrlKUmyDfvWRCTu6NbHQVl+OJSfCwhUVeChanNqoH7Jd7CiBMvi2FGNHWb1A0kr8Bke8KDhAyaGhMO7Bc74rO/hpXJB7EyYSS7eFd45IrrLrwrUW2/ove3j7ryCwRakV9evw7XX0DZVH+8j9Pr4P3Z+Lx95ar8HYkWIaRtE5h6HJeOKwEEG4rSBV26ieUGfiGiiYbO3wLREN7qpzpQwKNGWu63AxxEVzHMJ23bjA7ywq145v1BpM4Kb9kPqCBfKIT1DoOJZl+BAONf/P1mOq3bpLkgvU0dDjMp65k8st8w5U7wNIjEk+0JJP8gwRHfyEpP71r22Xo1+UJQUz/dJhZbxZ/gojDbOms2wz84u9tR8nseX2XmoDfYCEF3DS4esEgHZYBa55LTJIDljOL/qcR24AIfvu5YNc9K1Jjy3OePmkO/vbvI1Eq86SfxZD4ExzPiBXpUghafZF9HFJM8ncm/VL99WLtEFHtwySCQCYzvNfwNckk2E2s+Ql4VeGZLnLFylf++ZXjgBo7kQ8LX28p/2IdI3mITU8KOjf38DV6ePc2Y0IuNpcpDSL+kXv9px3bdKoV86n/ukzsi9aXGbGWQlN/azR4A3ILbKlnorobbE3wGeWZKnj0NjZaz2PBXwUe6rNMDAHgakZAlwbCxMDzQf8i1+8xRFU
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-s3-secrets
      namespace: ai
    type: Opaque
