---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-s3-secrets
  namespace: ai
spec:
  encryptedData:
    access-key: AgA8pa3gX7Cnc6q2vnd42aMuRJsaTV5YuC1lOY3bphHQW7kn0s07BRgcixNo7/W4O6TOuRW0DRFgvzVsaOw3u0ZhGle+rW2va6TUt9F8Uv+eN22pbUXw2SpDF+xTHmSbKVXvj3BWFO5qTkKvlPj7tjbFWOxqAWtHqXYtZJx1MAP9KoBnPXkc/UVz14GFWi/ynkaUgFo2XH1WE+5zLk/dKEiKB3/oJ85v7J50f6m3USqSvbHOiYZPiFNJvBDVXuwS0Vw/xCJ8rjbQgZAUhzP8LEg8ZgsQP8IA/kcTG01DSDlRf8ElECFz2zFuxp9w8Z4zYt2NbaFM3bZOF0OY59jmmT2YGifrzTNG7AdrWqMWDNAUSbAzD2ZuMwKorHcIniT7SHXPwsJm+iQ0WCon8tEoMZgBdd1jFSNneZRhQmmRCRvg2JrPxywRburoqAymEjyhdfKQzUrdCSF3r0RsLUQam6vHzyRPuCvt4v5ZKPb4MW6pRLooYvZmp7IrdKrT0/yUyX4B2CUt6vcNgEx8SQ02f+7qGLAcT0V2uf21qG0uArp3XlE6nGuCGYu3mcRWgzHdNCn7glYpaCSV8wROGgxYFyA7l54JQF0A8i2h8Lq/1ycSSGzzk8ZkKGG2C1tXwX0myReKQMRPCSH3iMLoSDHZmE7PIdcfhSqls3+KHR38Cmc+eDiBoXS+vUCWlM4KkCJ3KJg2ZdZ+6CsixJE=
    secret-key: AgCK0XxhSA+90JeU/CYhRNeHCAcAeuiTWwsdawf5VXuc8MDMpTzom+oKIUkA7QjnGSmjx7WSdlMCSyS9RNtZEVoscK7WIrrQVHKdmCxtFcdcpiJJZbc+7pyBmx8M9LXE7yk066lP9n/r5SZ31PFB65j8ZZbnePJLtsXJgMwW3uS616TtbPiBs2j+UsmNm388g9TVIO3mTqZ7f1DoVv5WFyXqxag1aOnS7tYGWn0893mPS0RbHQnrZ341WAA39jmiANHnj3nwew5dvlkHhueKwJJcTQUPt4UH0xtc1ijYqL9mZlL+AtICr5cnnQ2Tif9xhpHQeFzKyzHXR0eHu8D9f2QTdNuZ/BhZagLuQAnoJ62L7WVKI9Y7isyv7N5yDPCvTVv036pKwKk+MZjYAABG5WQBcgj1DLOQKKyK+ty+X3BpG4loZw3SXh2Utya/MI1mHChlAkagf4CntwJDnVNZMDaiJiSPeGjnJakG/X5GV32os2m29q/wfRIFICABgC4sQny499XoXAmGzmx9Eq4d6gvI0GJrfI7sH0PZBYL/WyBspj+1iDiZkhhmobQccVW2QBgzDvI9d6367DKw6AlmZ5ZnSrqy3d/JuDiqG5claenm2eWVSZlUPUs/kyy5j0xtUeVQ/m7uVOM1yn3Ca2K0jF2ooyl7QEy25cgTNLcWG/aFsn1Ahr0uQ7Oh/mX0mcP/RtF3pVKVBE4bCVc=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-s3-secrets
      namespace: ai
    type: Opaque
