---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oidc-secret
  namespace: ai
spec:
  encryptedData:
    OAUTH_CLIENT_ID: AgCvCxY4K8VdLRm3yFE+5qhHXB80H/+sv7Uy35xd6sAcIen09jxdF+yQt6ZFcCqohJBMx/oWw9qDT3ljUg+TK97TcASjRimDJGt16HdKwHJWUx3Fs9szwtzd19iL7ixiBdmRu+lewHP7DBNBigzjVIITChf/fUylqCcCVIMsbQ4bVWtu9gJ3WyrJ1ka2hKGg5qfhG/art7DFQPAJokU1DjvudVXKrerIDEpTBHMpevMUHUwAEpUrzxnebeMxlenuDRnW1G3Qm1YhdTiM9DjmqQFSFkwBIr6CPTdmJnYEeiN/BuIwOaiQq9ZagjjGxfQaDm67SJAc/7KQh/LS49BgvISAG4pOARtvoN8D9dqvmSIsQnvBrhSJHYvxq4eGn8suhIkvvmDB9PINpHqkcJb+ViCuLmSF8i5TcA9n8q1llRBTF/mBI5MzKR0hVcSPpgm8s2mOT2TUEke5U1ol9DfBepPppyJWbYW/YdK/TkYjkcC9+4Ujyi47x4YRZJ4EakM15pQ+cFJngY22mJEWmK79LjP09i1/ey+PwuSLhYY25JCrKQO3DyBXvVSNtzm+CUf4gruIOeu5Cdi0Lh3nqgPC5lPZUT/EbWwgv8eZJiiaLsJCnoZxPyY9LdYOe7JS3zlF1PnaPNMz8/BImn4LPlPBaulJpoZLT5YcELVirZCVzGwrVkbWxm9RKG58Co07kW45OmS7TWknx1Tu4x2Xhw1jcyOzkiTYy0ilt/cmXPNky9ha3/9EXtw=
    OAUTH_CLIENT_SECRET: AgCrVr7Vvieh8I1PO+3NFNp9NdHd4nOh2Vfy3af4oEMzjea0wDXGcyDZqsOK6WYt01UAckQqX4/GKPBC2rL6k7tFunxl5fuuy3y2ELHVRk/IOXBFF1iuhktvN/bhAig1Htx2Yt/0wSsrIsX8XbbU46pJN4Js6DK2gpEy4cQcgut8ognJxNXNLrN7IErvbbHnOb/dJ7/4GhZc+olFbMSS/Lqw49lG7lOE8dijfPHeGyWemdPF2s0QJVJt+Hp/qkOs0O4257zagwPCxEG1LwNZbxueh0pPSWKZqY5ZsKt7LiyKjPEe8SvCpZhE6BjRSb+3BxlI5RtzAsi/nR9pkfcPF4UeHAyhOun+xGPDm7mnvaVBj5XCeuI2gO+pyP/hkHCaaSnlTSSyzUYxz9tf7j04As0QQ4u4hT8S1Wxsj3idVneeKrU+szDIaUvErnsV5sQvPG4t6nNe1YLYhnrEEOoyhkw3fJ3zF5MveLLIdFJKi5VVmYFjZbpfxsM8CMnrq3ymIOOae7YeTFKxCno+mPsuT8FM0KkI0vPrssYXGWmyhnIV/AjzNnNK8sYWn7w00LBhPlX9mZg1/ZMJlrsxpcUeQcwGzHr9mpVK5OYMzNWa7qhWbESpha1188DVJpHRRVIab8W7t0YVX3SAVb5/kb2Us3w30dGmWOoMnSlxNK1Ht8d+PDKfO7a6BSJU0cD8Hcba6Jy+vFCdz9W/Eg27pAoC4m3Z6KNzDG+74MD0rwaLbV0Edw==
  template:
    metadata:
      name: open-webui-oidc-secret
      namespace: ai
    type: Opaque
