---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: admin
spec:
  encryptedData:
    admin-password: AgAI7T+1OLyRZGLQ5ZYrEiC+ivkUR2yiWafM3ORnd2P4bwCOQXWwPkBePWhRiQBTXtOQklrcy8pdR96EyY6J4tT3kj5MeySquN2U0gzzy0C+M82b8X5aGzcsa+d57rL4bfKpcCqY9FLwJgEpW+T0quzq+fGEMziR60Fsf1EyvGRpE6SPL+FsHJa3EvdqLoOkOUyGVPpTNNQOr+fMm29x4LFmql0CLXyVMddC36xWRBMYJsTSd99ZW/9RZkYoGPFtSuPFA4BzZyvMKd0vorZx6UEN32DglG2AXtZYLv9CyrU2SoV+aqol9+byMGsPbVnVQCHargLn7PL3EFrdrWEs3y+p2wlD6arxgEukP0lbHkWdleQsn4SMbB/Af6SPrlfJoDq0NFpedejGZUH03tjFGdOuSnAXKssDB5XsdrWX/l6iCC3zAK3Y/Y6QQbGl1/Jz4wbDqTqqKmJHfDELgNF1N/2Qvj8KvO5A1tx4sFLpcWUBEDYSJpy9QjQvdWLxNgpFhjsh7Oh/lv8akOBkaPsbPJxHOhW2clTE4xrih9XeDKrcHSnMzx/pIVKT4zs6EMFz4TgyBtn0AjRqvv98hCsHU21bNeIkElZzl7AiuPQMOC+DiSSngc71q3ehm6NwIAV4idDRIVkD4+SkG9S/fzuQf6XsKLXwszEvEQmGUYcX/tbELjR1MbHGjlHfCj2ZnCSiL/dI5caqfS/RPWT+rIG8eo3xRg==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-oidc-secret
  namespace: admin
spec:
  encryptedData:
    PGADMIN_CONFIG_ENHANCED_SQL_EDITOR: AgBj3ircCSr7lBlu45d7Dwq4afGtokkvYuRlajftL6r21VxvUeVDb3q7DfOcZp+2+CJ83oX5dqOPzZRUbWaDq7dgoFAQdaun9EH4Up30zbvsmLz3mXVQsiwE5HQBIZq7zeO7EU0HEuuAiyMedYC6z8PtJ4i8ji3NNtQw69CDFF5Ro0DXy/VRdb13eDO1KtHfarX8doJY1OQ30K5QOM/IbRFJ9iLR9+FzmfmvGqX9KGXR+UgbHgPoRVZqgaLbktIoumJdLOuKL2wf9MfcWJO4ZWRmtHmTJZZa/gW6qszvL2GEhl3814MdGDX78w/snLm2HOa9pw3gsppNnWayKhbZP+cwncLwTLcf3u+rQYddQJsWFY2mTmIIsdovJJJvEdl2RTr9QhxYPFn1wa7tY2MFd6FHSEAfq5wW5JjhGMtPbDAiBH0UZ3/NK6J6R0tY6JxNwvv+zGIsG/d/PDUamTkq31tRQuEqOZSZsBuDJ4jzc6MYf5j68AiE4HAhflB39JFK1myHR2w3PIEqU93CPV6lh+m8/3rRKuM2qyg9++Blr4C+1Lk0670xdUOjyBnWuF/NxDXI0SF2lSM3IwLX5fmKhJiYQt4XRLeiEKSg31tHROi8FT2DN1RnnyXFjlK78sybuOTXfP1SR5yQ0yHc3vVf5auoBYBykev2faokXvGVMAj1Smw56f+pCN4GLpJm824SAdyR9P7n
    PGADMIN_DISABLE_POSTFIX: AgAlSb/hdbD6m459nLvWGtBCXP1LWV/bGCrai0V6Qnx4Qg1Y8yqwZzjJPzPKXukMjGmPHXIurA39ztqc7HLjxQ7sDZgwz0NFQJy8yXxgUwOp+XjihmB/jYhlFruUQplNwulGglBtZeQqepKy8xtWNb84420tLLvYxGnIynoIk39LKIn3WM/gjD8mIj8834CAYG7vIYy+bcXqpWwsPl1MeoaxE5d28BOg858mqmgpUb/lZWE2w7g4f58sMHeXxww2CQaYWnQ/dbklxBl+fS2CHOZkSw49YLCkyv+HakUr4HgN77ty2ubnrTq8nOMdA+WW16oR8s2Ni684ZvpyN4cURvK5P0z8OtmuhOKVVv94cSC3i9hSgnYovG6n+7YZ3EIP4J5esW3USWfdA101QJh3L2F3qyzQMGtU/rmbTZ+6lbqvK3ZJaYDuyLQJ9G3PYsdUWhmxrmZ3j3w8Sj7bo4MxBBJH+Bwkhy4JqPMP8EG5tTQmdWafJpuN4Cuuw2zi9e6F2j/mqb37wgLb7spPdZ8kG/2XnvuyXBLGa8YWl5m30BfntnQ9CZWDE66HRxmMYtjUMNtTAQIVfW4al5lFJFTYO6OXay4JXiQdSYzn8CpzXqzsBslI82QJl9Q/yGZi+rKkxq/N6WClC647nJVbGnUujEDKBS8q2JlTB8J7xsQuIhhsGo4deXB7697VY0/EQSyo0rmtyr80
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-oidc-secret
      namespace: admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-oauth-config
  namespace: admin
spec:
  encryptedData:
    config_local.py: AgBfQOZCaTp8TPPEDkQzjGOiRZF3dB29DACSJIJKO4Huhws21avT5TosFi1sPT5swqRI9k/0/w6pgohRaaGj3A6cf1EmjCHmdTgwCIezV5oOlWD2wuJY66WRLjzKYUndg6+pjEZpZw4UiMHBlbcGHymeMSfvOpU0QJQA3vA31f0u7tczhqvWyWwcLK1Hl+i12PyqhwqSsKWMUl+sXIIy3r7mxrURuqkuXW9XtBcS6HzHLqZpCDGsAw+laHvM2XLq5ez1raBImMk34cV7iNjR+f97BLKIO54GO7RkXeOEAulG5irqD8yljKfN/TO+Z9B4L3D8HDLXnB70cFN28MsHj8FaFXN279BhQkOe/U4yTuvLsUFYnlhqB49c0F6PN6SuF2kR7PIZLNZDwCofVPo56U4rbPF8UbrCB/AocOhY34xzZl6AJ89zjOdBHGXx2FUMKBHf3Es7pJBEumCrROkrvDYVcBE3L3ESt37HK7UWqTkW1Ak0h1MSLRflhJ5JskYbfoT6FEumVIBCPCyzCx8125qgGgakpARhTxfwccOT/TceudmIrgmP38r5oPRF5HXOU+1BRcNTkzprusN1gXwcuwySYVP+Uj99hfGuIxPLa1Xg41ws9iuYzK60zBEJ0mwicHT7f18g+bSrq4nrFxApKC9YR5LNPLDqJUqH7IwxwBJ2EPoeaz6S7eqJc2JizYXobf/7F3mpd10r8Oq3Wb1Z4Flw08pNd0+5gt5uwLe4ZO1JqjfLt61Up0XFXuUIsI7KCO7HAj0giXE1hobx/KVnzgw1/J92y8Ro1Tv8Tr0xOGVyc49UkavkZobcm9e9Sn4jddxtDQkeWLrq6/i5dg45ISogACQXOIDjqoPagY93VlLClSvYvJOz7j3Xzqh/HIkQJ564VkAMCYFSpSRhpgWIcm/cfdkonvV52k74H2eloCV4kGE8/muXsY6dX+QUjfoHRZ3EU3trrRMzB1CghRxdJF67WU+xW5DAnnH6lVSdqzm1gO32Zl3JDvMIjlij+Y0slw8/lbRmmTRp6sb2GXG/cOgzch062h2kR8ZcCdyof01+8S0hqSBYdLJyPtG4OQRqy4aRfvcT2IoigOgfl158C11ipra+Lgs9NO5bZAFgnvGftbZdbr9yxfkvojpQ49ESmbTaMyKyx9rbkRTDrTMNJ2PUBo/+u8Y8AUIH26JpsROeTHWw8PLFlNjB412boelrTnZmbQEC7Fez2xvIJQmdeTWYREADggh3Gdc/jtmeNKxenpycwu/XDdeUZxZxzBNU4eKxImr8XmWSbRdTWF+juFIIJ6NYoI5/TG8OeIWFiZ2RwFULZcqhNDWPBdtiq7iCYQaWZIwNAU1FXOBJTGQhOYyfppU6+eN3tW75yLHVcuEJwRsmjnevDdIeQV7RwELPYM4OWmeYR3ylJ4YQyBOcJDtKTRvU0fcbkaO+h9LLpiLYADoplWLJ3jQxWMfdID6UOkO2hfwWAbdfjd8A6CxRzyI2lg4ZOak4dsFuIgvlY5uPaPUE71hhQW4hn6u959H9wbyzVXq4Z6jco+WUAahv5iRNiBA7RCayZgc5UutDDAWlei1NERSBMRJEmAMavfGiFukyxSkte3e8iOujIziBwXRV7rjD3O5jScJScKN00bZHbaT7QGyFRm8vPWlcTDjCJlw1/NKTyXobklFUR36VH/1UJ1W8L8I/PJ/KMX7wC3p8ijYRKcF7mgGY2q6Sm7QvsPZhOxQbNBlPMK6S8cJoL5DMXQ==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-oauth-config
      namespace: admin
    type: Opaque
