---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: admin
spec:
  encryptedData:
    admin-password: AgCj8uZXBdVWYpDliaGXH6OSMLQNDNZ+RYFjF+gHvzk58q5lM11dK9IgAOTy3HSQe2MzCrOQyaMzBKuG0z74rs2Uz87mLBwuZCKJju0SWft3pQylW+GukeN/af+G+LEjPzXxKRyRQrBaO/6r5grWIL5cqP/2baTjTWrE9SGLDgXNSFvXbZeyYhvi0chmaH5MTQrfeeFHiTg63MqEvP+WBRqqjnpI3YuEQi81Ye5qfsZ5qEdKZmJgPAuUBZvTTj70CzP8cSoJ9KxuqKZYUZG6anbdOR8a5SQW5QLGoXYOwcTsSOIM3NDSxbgdD6YGRRWOqjs29zPWde4LzZ5UBjOcgpKSqqVFmRxg1tBS4z0yj2r8vBZHbOj4+75mslrLOkwIQ0kBP2DdfaWeYA2V6dRIy16MnsOtUG4VXSFRydshx8YC2DnVd+bOGqjtWMYZlHfQH1Hm6I4Uk2AgnlDanmdbrcxOV56dMZFud2l8vWzY5OzngetilvgZ7j2qqTjzSgCort2INMIzLOuOmVlL+aEXURMuj7dk9+My/iX7tw9NEZigmjI/sTFuCD7efug8NhpzUMDN7F+6pBu5TES6Nvre04fzMSUDl6I8A7xSh4OFRb/KVRqjXCXx4e8juwY9jHuR3qoBVgNs8NpVWHDH0wun5IKLeoLMJjLjslyYhTkrwbUESdBxACE1X+cdivmnldHqX7xAPDKgsHjPYMKQiVU0jKGQgA==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-oidc-secret
  namespace: admin
spec:
  encryptedData:
    PGADMIN_CONFIG_ENHANCED_SQL_EDITOR: AgBWgiDXHkjpVZFII4snNdXzwtpB5M5u/0AU+PMuiqrgkN/iaNHqNBxyBbZsAyHJ9ry+hudv+btyCY9Ty/cUkTCNJiwAtGnp/Oh2qzuunKrQYIQ7igyZHp/GosSTCUrLh2ls5E//Ih5YeSUcpkIsV+i+77xr5Lko9BZLoSZXbeVQzJXRqIu2jaa9yA5M6ae+Qjm88TbAOr/bMJ78aKGG3ii61RuPStDieDafKnFOlh+Wr0TJschmbMU+FLfumOn9Iu6UOiApmrOgk8RikBabdToaCW2asSfthcLvsyLrP0cfuIzA26mOXtthQgIz8pXeWnMqyDmMQm2imZHGk85gn7EvDObJJQarxtXkT1sBz68vT5bA52Ddv4R43BSZATheHyApkOwINgjPGjd3O2F0DNwz3G4VJ4f7hROG7QdzYXYlpJXjvhSHOmWnQ5k2Tw3amaZ8/laEn6GIfjcsdWNup+4UjQdDkwUGYWZ+vyEZlQ/mG8VEQh/tkU/8DS9PAJrsPTHfWpxgxrILKs/poG2UWzVlFraa1lVBKrOKfN8/7Cx5K0Cu20R6uyCwNNROn9NZOF2fdinmAoDDXLXUvqnGimde9EW/TgDiSwTlKvkEhE37MdFeHe9fMPWAB5/RcrqRI+rsv3e20nOQqSX0mEtkGaLsDZ6beT18lvrja2n3YNFek2eyZ24gSwg9CkWDTc/bXVZzfeBM
    PGADMIN_DISABLE_POSTFIX: AgCw4OSXgIVKjyNCVWnEtUGWHwAI7LagKuBYxI9f4oFJVhENJNeEFdBjGChd7+IZxjqnKOKYR5XMJsRPrfS0YSKG4y+F5KbMV8RiYkDd4ctAx2bnwl5edOhQbc6hKTrFAwRQK7BNnYlT2Skf4qHzLS+IP/wsTu6Xwqd8ASdUtW1iRHpDQXfI0R3WZGi3qAdjQc3WrezPQh7Q+6b6hZLylTRRzW5Sdr6b/OUG01slVSLnYMQ+wK0vErGmPc8UmXehYPl7m/OWXAplWsrufyZ6NLnYJf7pFr+Pf8Y8NKHAD9efpLPVh9M7aEqYU5r2aCV6HGzQdbeLa0rXXMwPjutgjGqCbwzW2PXvuODIlPNwncf9WUzsov24R5poeUe3mzDY3bXYGkDeWz02YarqQE2ul9Qtj5lj7VsIiFBlqwgtipIUZyrdcVOZkWqEruk9krxzdK56Z4F9gnYFjYbkCIOGDaoE4tCRV0dQaCFGJauOjZBzmZUzmz19apEIRtxw13e012OWytc8dL0gdvweyvhZNIOQfvhWOJyd2UdPhgYJvLlMEwsE//SM/zGAs5fPvUlWhBHuoEkobFeglcg7WLPyo++KpcDYeRMyQcPLu15TFXqZ4oZEpD6uSx/S2Ep1fhbxNhE3VPnytfle0h6ZqzIKVPnRdfdTPlDjoXanZbgvFEP3Mt3Qyq3jL9hpWBa0b9YqWtdh258C
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-oidc-secret
      namespace: admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-oauth-config
  namespace: admin
spec:
  encryptedData:
    config_local.py: AgAt0JDYpMsYn71k5n4o5D4XcWWFkxHyVaBdbNU+LMbRs+dynceqx+dKh8DvS7uC2zXJz43OZb38xjsyQCv/+CV9Fw2ZFI1PyNDYS1kTgyJDyVrADwLM/Iy1FdmLRnsuT/QL1qXM0pCjupdx4Z5ZzPvd66buC5gvvmVbTcf8jfdze562GzzdyE6JZY7iNrnkyG7PSI0ZgGtIaaLAncCY9QpHgfdkH1QpzhwhUUABu9ErQtkuHbdZZ3STUJeXN2xvS6F0Gw/P298voC55Lq/gIlBr5JJ97hNR2upM+S71RoMQf1lzMz+d7Yxv5nLhaUE/Mvf4Jes/hskAjLZFvBIyu5OnLvuDznQ5BBpGoTfMPD1Y4ZY73HO/0IoN0jJ47ub8J1jA4BgjYEv1z1NAEar4coJzgm7/hS1yPUjCMDBStrgUx9S2b9+3ufQb7nKt6/6r9qxW6w8Rs3+q0yirJqp9r02q3H+IL1vUfNdgPaL4vuHJVJRoVl3acwjYoGz4nL6nZLxnTEilzJQBdxzXh/B0jvo59byW/ISXUbgtMYPGzp70C70vpYNDQjQXPkTN1CgzTSQq7x990TCxaKSMxPR6Ua7IpLhtVrcPmfXr11t5iLCIROWKY83dVYHBY2W+dqMNrBWDNyyl6YPFmJxeyLTwpPLyH+dbKxXYgaNx5sm3r3QLxYlziKw7sRa8u5Yr1Ttt7wm92BTg3IvC0BzzD9EbvuzFGYg/Uj6PT+jvf6+72BD4WVzy28o2VGTsYt4OLwEcMclbZdWkWVTOY40kGm25g217kzO8Yj+bVDptDVGiJixTrO4HBScLhOmHfdTYbVXgZmje+KEyqX7uEf5TLzMlBvmL1TAzMIrBL5S2hYWWWqWQXNJtyi00fODCOP/3QvfmnNJX1Yh+vzu6foERHspnI0g8HDRSUphVodvkMVMX+WrhAtxkBMk4+RA89C1CmH9aYfwdgcZeZDs5iHiqY66fat+dWHrQu5rU5isBrj8HgHGq2t+Wb0SAjKuKhhIjVQpSVOr1l01XEEIiq/cfK2oqCDEAbISnhgwn+kbFvHBpjTbIZe+ncuqkOFo+q/20ymOlE1Wtdy2vGm9/nmdbfM1so0lOLoNA5Z0WgUiGew9gNFzPHhL0lbEburlnbsSeVZH04cm33nUK2DyEH2xC/9S1rXBfNqboopCPtOk18jLAx9E7h+zX4UjoP97NHGLhiKnxbVY+81ZVTK2Lkh+ALeHy2Cs+25qHLQlYln0gy2vbOQ4AVE8Vg4/DNK0YmObKGFaurpgDtSjI4c4jH/DzwHIkf3ZBVVdiyObiwaIHf0Fj8cTzfkluoNePixUebuvZBW/AzTlDMFyuGQAOVnKXpAFyg6IR6qHN4KNFusZgjNpsUd8VIpsvKto6hm9oU7mMpiQ3ASbRP7AeSW1j5rN7A6LvOKBdPXhj9aXM8cMPG4rTv+hkspbXga41ijSk4bzXQMUY34HsWdgrVnmKbRl02OK6MKz1EuqgEjoP25iEkcyE7DLo1IPEnTMJC89306IAuDpEMwkyjsu55CNrqTlj1WEo/C27TekKd5W+OMRbY+6gYNvCyiv2ihFMaU0RklZLOR9Y+hO4yZvkqo8ccqb8TPLpnfsQpIEWaxO5jC09gMz8nFOeNfE3jZ/EKeb7bR98BDlbchRvtpqRV5fsm51hy0y/jSVjvMyav2ErNT4xU/85Un2i3VF7Lnaa2qFFCLx4jAAzftw5j2sNR8swQd083xqIT0094GaQzlZm2F/00jJX4aA=
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-oauth-config
      namespace: admin
    type: Opaque
