---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: samba-secret
  namespace: storage
spec:
  encryptedData:
    password: AgAB7vcPKX3CjWHMSHnFGTFBgpjqDp/7zXmnBZTxIWm9qox9YZ+JrqCFUIYxiysbUJcnYrOxRFprTBaG7CIDYRsluUmjOETkZEMqz2OREfQS1OIWCGkOfvbfu/PSTYpbeN9Km9Z7l86oiD9sV6fbH7pz2ZIxOs+/xoR/ocKqCAmheNgj9FbHzfDHqkTanwiVTu6A/8pCpOKtyVJhXtQywFsHYoglUZh8XfxMSq0CXX36AfvDlmfC5kSPNiLxw+kCcgk7uKNaNHVgrJLoX5oOcOTvq4afdcoyQT+riWkDLLu39n+AtZrCcRXCdGRf0LCkWQmGlYXr5m1pl5yaxs9ypgWCq+WA0dJAWh+3kq2jVHghw6vUH4IL9ylzUmXSsG6h7u0MgXI2VrjHtW+IB2mDe8ANu5/m45KwQPkd0i2cmria5HRGHvBjeema0a4BA3VxfKgVK9L8eyWkWp36CO+kh7nI83LxKg4xMO2B/LMBhjjduYLv+RSeZYZp0//3padfIRxF27caZZcN2hm253MLlD8nv50JQThRkoh8Un3pUT5xdQ/dqsiD71cCaUaKks/hnT6vEZq2pZIuB+Cg4cB+XrotRZO9CoS5wlDsHdRnHyzELF3CYRgETrRiHr9nUU7MsFOKdOE9i4mUkIb7dOkyOFpXCdLaeHp+n46T5V6ZVyo5Ypq/jJDkCD7V4qqdN/4eI/YlN17CGjMoAMtYEA==
  template:
    metadata:
      creationTimestamp: null
      name: samba-secret
      namespace: storage
    type: Opaque
