---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ark-secrets
  namespace: games
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBUdTY+vXKSmFefjiaWnkOCHuvV6yklEAXZ5r3Eqn7ibZaM18aOeY85RJMCLDMWhDfaMbPEwnAqaYKMG3uJygSj+qeg9qva6KMyxe0v/KGrdxFfrS+FDFze8ZBXdkJAP2LcGnzN8d9KwKIsPepUz7brGlh71isCelnVFfc3PFdfTMry7OcC3cbNeQyA+Byj6BmWvPT+AcRjgAZ+FgoTWZB+se4ZKLZycnXsvvhhgM74doPJxeJbQke/VyLYc2rIzSP4UYv3b10ARkT/fiEZn0OZNPYNOfkwaw7KU9o+0yFH0/H2DB9nik+3sF8ZpbSDJ90CM6YJrp7vUFwREZOTWKbS6HbFVm2eAFa7ySsuTVGXIN6Phr3cM9s8ngxJLbma7KbObc+5u/MF5YQzH0CQyCDI89woW9jdL1FgLvz7lcG4Ve+7QZvEtYRn3Vb/alExW9I53khd2K+vp8QGmQ/vdoBy8lzl1Mj4k5xwH7jCwddkNiBcp9Zcv/LyGpYJ9YzO6BuXIzThSB6XsEPdgtnZibZGSv14rtOkyNpAxyLGGq0dX5ufGGVxIAsOoJKK0zrnGxtuJPPVWxj6qEV6G3tPyvUpy9/PlxIi/powzOY3k8wvaqfubI/ZNzGx3A14iu7Z9GUS7NBfh7KU5ofEP7PrktepNBB7uIGWAkaFr5KWeoQW4JUTMJ+4rPsU72efqooPaEFau35knXiSVGFC9D8hmo5p
    SERVER_PASSWORD: AgCNuoH6AfOdmyU+x71Gx2YR/RHfjU2pzNNW+2I7DIiXmylDg+Ch6KddLfZn+Ise3iT6PWDAp+0T/4yr3L/K1z3B+xf5jJhftZ5kzcDG0MlGkK3iPImdVJXlI44jTN8qJo8V5KjZ2y5UGlbcN3rdeOIXHR3ZIzdpJ/TpOkyUvD+qeJx56OixYFZ7Cq66azQt2LuMIx+m8Qt5jaLjLYdwwwP3YOQksQG6DA6/sYFfPMs9fniXXshrrrIg5Q14OZaZXoaf+lFoMHqkFNpw6F54kP/na3wunLTXF2MRlwNkNk/Mw0RV4x2fkwZTfhWQ+gZKqwjGfvUoUPKKuVJ5x4B6ZJOC89rSO/yxIH71yfRYuu8TN/bWFsyLapBjU5/b1n7Cv3ZtRKTMb3RqblAgjFU+w9zwA3KA45JD1JgUfyudqPbnbuxOwzrX2OYbJi519jY+y6Wfs9UxhOqTAjZUSQVjrHTUfRTirDJigI5V3biYLwaAInLa8e6BRPBxvyrCW8blIKO3jbfFJx1cwRstscuuPkFAuByOa96vV3w+lzUlR9/sYh+ZeVflKvKiqDp7wHmKtkUKbmclQTPuKLn/JYCqNkyOvFyFRCoT9QyOhR1WQf/eSzb7ygWS3py+eXtloW4Zf7ImIORGchOroreibBbdqDij6JMOKeiTMrM5V888QotgS/YgiZYQV3jrgEUUyaz9iY0=
  template:
    metadata:
      creationTimestamp: null
      name: ark-secrets
      namespace: games
    type: Opaque
