---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCzl77vY4jzfiy2LLmC219qlJurE23JCt6RTzrAHj5dqq/6S2Qsa4vky3aPTTn4gEVyJUDBRhzOVxDJKk41JtQ5qnMVBlLbVlybxJsmu8aw+nQgFA/PD7Z1yVoZgixbsgaBLp+WFQb1bRZ9YIimTYFU+WBrj1JALKLq5BdATXOY5YdCoGW+IK/J5s9gJNw1f5MUwjbITzyoPFGbUQQkYUrzVhercyDoU1/IbTGlzASCOmtjbki57PkqBN04Wd6kCO81ookSFyWmS3IvCECb5opAnz17RBdJc9JQvComr7RqZ5eXpYTe+IfaNHjAVMBL9mor8NaTuMrOxMpFdFOQ63W8lND/lLZ7o54Z3qvzFLRMUrTXzfIK5FrHe5TviSE8Md4QUR/HsXyMkJiaslfyBuGTUD/xlF9GQS+ry2NvZRVg1OlGco48dCHqrfOvQ5dI04pSxPPjWG7wyqCp9rn24Yb4A0W2OkdIk8VN33pe1B6M0A9s1u6yJXhIaf81VhW3piZ3gmWfSPhxhraRnOABF8cgdxQxtv2G/tSCNba8T6QXs2SnYMVEZ8EF80iOXHXbhfpgs0b+ykr2TG+BSYg4l7JZ/iyoCv70rR9YN0LsZ87JaA0b733q5R2xDy0t0Lht6c5aZC3bgAdMNrp55LqhpZFyJ8nGXOLtWPggoxbCnYQ1Cs+MZyiFJldnTodtWpt5HnUIP+dhx6FvtGM/PlQ5eN6dFQ==
    client_secret: AgAUmE1hS6IVUDe7D0wblpwo3SeFGb4YGlAQtmcypNuDEaHXpKR9J0n5tTuC0tHfXXsNB27JN3hsRL/Z8oX2CGT5lfnkMki5ITACJift1YcuELHrKp4T95OvAcEoUzWNKbrlznitTMDdciAw53N3PEL7qRRvsOosqKgeKmtl/U3x16/v5zCHl+Jc8p73biYkKJgKaMbI213T5Hs0B4LljL7xSoxmIRiB+iJ9o7gonJRxA7mu26o5gSh7l+EfMBx9xg6VmS1Moz/bHhlSpCeZqlsb7cKrc36Gejto/74ATlxfJLN25q1hwEj7VuH0OLc4JQoSB5rS71J0zSNTMq/JdNlxJM7+g0pkpEO6T6QwpSDPaj6DdS6DBAC3QBlLEN1gdaIDs1d88pKipiufkoTfbniHeI3q3yzIdZZEvomN/NRsTVnYDo0sRDsA3ajsebnKO412QCE8vzXDXCLNNYN8opEg8B0CI+lLJbHhuO80gLrvGFd7WWHRztV4FSPCRTM0/zxH3gzX+J4WOzTKSgSvbOCT+lIeQ8CxC6Le9FMzPl8cKTMXmGWkvRJvT7gziNR9rCT1zCP4JoiPdN+BVMgWStMCgsHcUBFq8jnkEHgR3z7h+yijNjIZbOMmVZLmEWqjlPCW8x+kOx2nmyLXnL8ssR4sIMcxAFNbnKUwWvf3jDBwN7gECmZoTtbY7Q3XZsqAv/8+SEvqywqBqhGCMLh1/mVDwFxp5lQFrJ7MwJRn6oykMYb4ZC8XiFRifZ8JjBFB8dyS5UURnRNhDsvgsCbc+XU=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
