---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-dynamic
  namespace: kube-system
spec:
  encryptedData:
    moonlight.yaml: AgAqta6NzT5ByjNR7Eqj17bfSY96iFQuVAhYu0mQs2jzoTr7HXzZQ7iyoPvM0nAmKK8tbDgK5a/DHfw1CIul1pygRVJ65dLXdifg9BC9pgwJ/B8DZz+vlfi4FfsqrJ2BvkoxXB/X/ol7B/pTtUJrgfxEbME5q+pPMzov3k8421KDw3YXJ5EPgDs5undIA9wAPrrr8afSUpEU5ZIsoDf0cpOUNtMMxiz1070ImMwA9HCbrvDyagYzydUE9sE7p0UzYyNTJndJ1dm9IIF17R2fDgH45dT8igCFdxWAZZE7W+FapxXUmQ+wJ8ibe88nRMczLQVOaBh65AvTZydDMqc2JlVM9+1bMqNBnIX0RLvSoqiWsU6hM99kFSz9UWFPfzOvWbfDS+FeODR/jzWD+2C+iLVfIpqKU32O9t84y2b7VWa/ke0iWPMeSA25yoW+CB9zFQFG7ywGqE3lwlulGvAbeRBioQGTXVQpONXCjEkYE+M6O1ruitslzIrbqZt1Q7iDNQJJ1VyvOiPDiT3BXKGlMJG25veWptIta7s3qmIWDV8q5nilFGyncTjp81ppJaH5OJQS7NuAP5dXBPUN8MwNALrw7XiOnra6mGJUefTFMo1bxb9awdXKSWocOk4Ip657WgcGdNTWcuWx6YVcW2AhL1COLMIN1iAtqr97u4jQXACr+mvG1AFgBkELwT0kt5FCNxlImQVTndiHujLX4Y18ZRkXJLJjJJU56Gz7Av4SeMM8z1LNWuFkHTxjH0qGslDx8PfVPG1DyDcPey8hiY19t52YdfxLZxTMvYggFCU4ao9tJcV0eLGTye1HFLillBxFKzfIaNf4dOUuOC5Qevv4iCEjc6os
  template:
    metadata:
      name: traefik-dynamic
      namespace: kube-system
    type: Opaque
