---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vfnc-basicauth
  namespace: dinum
spec:
  encryptedData:
    users: AgACjJF6LXmYqW7khZIpwZcA71IKDASCFOcIy9LCbPiHbiTy+GqB8sGKpH/dhj+R0k9x/Cy/t5jnpX/WWOre5BuIaf8vlaShQtcdVWgJtY7a2sAFRp+YkL9KtShqha75FG851wm7NFM+FFMH0By1sHJc/LiIyKBH77k4lEKw5a0GKUNYsySxdzPyNqNk8ip9BHJ1BhNUWDp9AV3H6RsCwfOL88mS3C7grBqLJz3zRgZzQtRlQ1Qx6hxp+yG/H8CTJq/be7Pfip2KX4ViYlZEB7T6+YDbO+HLn3ELr1XtuwDACWLwcPBsKp2DVb3vXXgQCxnDJXuR0ma9pkmCTLwbwP2DYdXv/nO1xhK3aB9vI4Tcg6rOTx95VZKZmBn5mFtHpOHSBRyJBtDhYNl0nYMPQuBT/rEmL17A1ctzyUENuDlMMC5BOiJx927QFEoX0sXBE0xZw+cfbn4VtRcQ/IrPRio/uAwrZ32GoIPn1tITY+Kr3sAEA88PeYYpfzIgs7YMQEni77gNdJiKLNtDbBR6QV/ndX4yYOCuRzP3dMSP41c7jsqwtUq0x6BSb2gKCJzzCM5yo0l8bdugxOeweOJwSopa9Tklm+cHz2w55hhF4y4thx+K5ghL61EPslqLeWY4phJ4nzpSElxVS8SW55YJMTEG54EOE/tL9PsmAjw3PFBDd4CZRWYj9u+sTuL2KlL04yAm2/FE4hx5/GTP/fJRK4OkA8h756qYyHbmgEX+S1Ii4zLxVJmvGNAHTGrgow==
  template:
    metadata:
      name: vfnc-basicauth
      namespace: dinum
    type: Opaque
