---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wetty-k3s-ssh-key
  namespace: admin
spec:
  encryptedData:
    key: AgClRGsx3NaX9/OY5UpF+Mp9Jvk5nm+Mvg/DU8jJFbryeEbcDa3tDb+jb3Ojh8xW/91Iemf0OTL9cCCm1iha5ZWrvRHL7y6UcDf5rcDEXUBetBF9saaVYMHgMY6nnxZ+1o/jhCXSfmryVWMnCSvSoN0gjaFMQo8kr8JxyWZue4PIueuNlq4NUaJF6hdevIHJ12gtAraCXc8+sBqUrpTf+cIgFK+f7pEpN7ILgyYqJ+lzoLJfnpIoWCpLSNeKfhvR9+AYYBNonLAbxssaDxtsZnz0+GlQ+x6Yq9e7SFTGFUlDgN2e87C9NFf6uKNRf7BwTMzWNBN5BueKoiAo1EQ2RM+7txkZtBsHl/wbwmjVbZIu3hZrRuVRVhRUq8IOHovFPCAiwv3yiF58YkD0a/fdHJn784KSC2JO07CY4d6VonQHeMqn4QEYzmgII+CktUjxPs7bg2dU4B/BK9jIRu9uJsT1BTWjqi3ZkJCrvC/mobTWrJ0AT2HKNswvT+7QisnxPg1PHMbRVrGbsCBObdK2Lgr9k6+HaxgfNOOy8zYiv55y/FVdQQHc1cdcjo1yJ2g0eSEPL+ebGuFhqP+0aw4nXtR+YsFgOwT9bK1WggQWgxjEJMcD7f7S3cqEyfiO+bNUCGTMMMOet87xjA2Qq2xLNHkbfvq2AHqiPCDktQMxV+2kDNWnO9HaasBcIbfQyw9OR9jEQyin4DfpgJlkODPNd4+m5ZbBzW31OzX0LKg3aekuEvIhLj+FQhIxD9mLcBylC5+hN9RU2VsBPCWQpNfNCkcVAt5tMCRJx2P0BBNMV346qJmEwspLiaPbK6MSHxXJh843zaK+q1M2P9TSy9xmLFJz23MiwfSkMj/1mylAGh8oEEXb8Twxhf1JoHP7VikrarxL1A3K+rw+Jk4pY41c2CT79oTodR34vac3yFvwpixcVCUI9LrybTKJvlyOn+ZSjeookl/a3iaddrViVmKZqM41Fc1RJuOX8cbzk6E5l5EfZmKpNJ3q1vLvRzCykTWH00gUDws1tjO04u77iPW2OxeXwl8CzL5UK0PDh74QIVcBztzONRYBG8XAbNDVS/zMKoH6Bq+3lm2y0DWHtl0aEjIzXJ8j8cDHgOCklvLf2hpuiTHPQc+rKUdNUr2hYe4u5Y7C4ScWgEJD7JmciQOAS4qqQ1wixKmcfOtQIxC+tIqAU/D2sllP71u6uy/gwACfuP00gNvGi69BYHjS7ezu6Tj5E+/b3L7I1W1ndz9tTdO8c7B96A==
  template:
    metadata:
      creationTimestamp: null
      name: wetty-k3s-ssh-key
      namespace: admin
    type: Opaque
