apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 5Gi # /config : DB recorder SQLite + .storage + custom_components
