apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 20Gi
