apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abugeia/home_kluster.git'
    targetRevision: HEAD
    path: apps/security/auth-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true