apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.2
    helm:
      valuesObject:
        crds:
          enabled: true
        # Force cert-manager à utiliser des serveurs DNS externes pour vérifier les challenges DNS-01
        # Nécessaire car AdGuard a un wildcard *.valab.top qui bloque la résolution des records TXT ACME
        dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"
        dns01RecursiveNameserversOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true