apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      targetRevision: 1.8.1
      chart: mlflow
      helm:
        valueFiles:
          - $values/apps/ai/mlflow/values.yaml
    - repoURL: 'https://github.com/abugeia/home_kluster.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
