apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moltbot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abugeia/home_kluster.git'
    targetRevision: HEAD
    path: apps/moltbot
  destination:
    server: https://kubernetes.default.svc
    namespace: moltbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
