apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://apache.github.io/superset
      targetRevision: 0.15.1 
      chart: superset
      helm:
        valueFiles:
          - $values/apps/data/superset/values.yaml
    - repoURL: 'https://github.com/abugeia/home_kluster.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
