apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webtop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/abugeia/home_kluster.git
    targetRevision: main
    path: apps/tools/webtop
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: webtop
      jqPathExpressions:
        - .spec.replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
