apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wetty
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  project: default
  source:
    path: apps/admin/wetty
    repoURL: https://github.com/abugeia/home_kluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
