apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier
  namespace: tools
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier.tools.svc.cluster.local:10000
      group: webtop
      sessionDuration: 5m
      dynamic:
        displayName: Webtop Desktop
        showDetails: true
        theme: hacker-terminal
        refreshFrequency: 2s
