# PVC pour Immich library (photos/videos)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany  # Nécessaire pour le serveur et machine-learning
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 100Gi
