{{- range $name, $config := .Values.apps }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-{{ $name }}
  namespace: tools
spec:
  plugin:
    sablier:
      sablierUrl: {{ $config.sablierUrl | default $.Values.defaults.sablierUrl }}
      group: {{ $config.group | default $name | quote }}
      sessionDuration: {{ $config.duration | default "30m" }}
      dynamic:
        displayName: {{ $config.group | default $name | quote }}
        showDetails: true
        theme: {{ $config.theme | default $.Values.defaults.theme }}
        refreshFrequency: {{ $config.refreshFrequency | default $.Values.defaults.refreshFrequency }}
{{- end }}
