apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-nvme
  resources:
    requests:
      storage: 100Mi
